### ISSUE TITLE
Badge Request: Ambassador, Homebrew, Homebrew Games, Homebrew Apps

### ISSUE THREAD

**Issue by kyoforkshomebrews** [Smumbo/DefinitiveIcons#1]
**Describe the badge**
Folder Badges for Ambassador games, General Homebrew, Homebrew Games and Homebrew Apps.
**Optionally, include an image of what you think the badge could look like**
![Ambassador](https://github.com/Smumbo/DefinitiveIcons/assets/49304418/af8d1eae-fdd1-40d4-9504-04c617caa669)
![Homebrew](https://github.com/Smumbo/DefinitiveIcons/assets/49304418/509b1b30-0990-429c-9780-df43f152dbb0)
![Homebrew Games 2](https://github.com/Smumbo/DefinitiveIcons/assets/49304418/c5738bc7-2870-47b2-8e46-46733404f44d)
![Homebrew Apps](https://github.com/Smumbo/DefinitiveIcons/assets/49304418/fd27e754-c7e6-48d6-9bab-bdd5121aa1d1)

**Comment by Smumbo** [comment]
Added in [v2.1](https://github.com/Smumbo/DefinitiveIcons/releases/tag/v2.1)

I made some modifications to your suggested icons to better fit with the visual design of the set, so they don't look exactly the same as the ones you suggested. Also, the pack already includes an icon for Homebrew, but I made some slight modifications to it, which are reflected in the newest version.

For your convenience, the new badges alone are available as a separate download if you do not want to download the full release.
