### ISSUE TITLE
Various Smaller Suggestions

### ISSUE THREAD

**Issue by Adlerschwinge** [Smumbo/DefinitiveIcons#11]
Hello again! I managed to come up with a few more (probably final) franchises to possibly add, tho this time they might be more rejected materials for various reaosns. Eitherway, just some small ideas.

Monster High
Hatsune Miku (Project Mirai/Vocaloids in general)
BoxBoy!
Pushmo/Stretchmo/Etc (i don't think there's an official franchise name for this one so maybe a generic character icon?)
PersonaQ
3D Classics (I'm not sure if this one counts cause it's more a series of games. Maybe just the "3d" from the icon?)

![image](https://github.com/user-attachments/assets/ee45deaa-3073-4fdc-93a9-aa93c5e8aae0)

One franchise im conflicted about is Starry☆Sky, i feel like it would deserve a badge too but there's no good way of translating the logo to a badge (since there's basically nothing to work with..) I've been using the favorites star for this one for a while instead, but if there is any way to make a badge about it, even if it's just the more crocked star from the logo, I'd absolutely adore it!

Oh and this one might just be kinda silly, but what about 45° angles of the dividers?

**Comment by Smumbo** [comment]
Thanks for your suggestions, I added all of them in [v3.3](https://github.com/Smumbo/DefinitiveIcons/releases/tag/v3.3). Hopefully they are to your liking :)

**Comment by Adlerschwinge** [comment]
I love them so much!! You're a godsend, thank you so so much :D
