### ISSUE TITLE
Etrian Odissey Logo(s)

### ISSUE THREAD

**Issue by SteffoGaudo** [Smumbo/DefinitiveIcons#7]
**Describe the badge**
Folder badge for the Etrian Odissey games. 
I can't find the original picture with only the initials, so heres the badge from https://themeplaza.art/item/65170

![Badge Etrian Odyssey](https://github.com/user-attachments/assets/12a4976a-4cb7-4d0d-a633-85bb616aed01)
Something like this but without the text.

**Comment by Smumbo** [comment]
Added in [v3.1](https://github.com/Smumbo/DefinitiveIcons/releases/tag/v3.1). Sorry for the delay.

Thanks for this request! I decided to check out the rest of the badges in that set you sent, and I added a few more badges for some game series I didn't have yet.

Here is just the Etrian Odyssey icon, for your convenience:
![Game  Etrian Odyssey](https://github.com/user-attachments/assets/e39d8632-a8fe-4475-9f21-303c2d4dc353)
